'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMErrorFixer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;errors&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;10ext3&quot;,
        '''      &quot;displayName&quot;: &quot;Error code: 10. Extended: 3&quot;,
        '''      &quot;type&quot;: &quot;Save file&quot;,
        '''      &quot;description&quot;: &quot;The game failed to save the game and created a .db-journal file.&quot;,
        '''      &quot;occurance&quot;: &quot;When selecting a world in the \&quot;SAVED GAMES\&quot; panel.&quot;,
        '''      &quot;fix&quot;: &quot;Execute any SQL command.&quot;,
        '''      &quot;button0&quot;: &quot;Fix Error&quot;,
        '''      &quot;button1&quot;: &quot;Fix All&quot;
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;player_out_of_world&quot;,
        '''      &quot;displayName&quot;: &quot;Player out of world&quot;,
        '''      &quot;type&quot;: &quot;S [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ErrorDatabase() As String
            Get
                Return ResourceManager.GetString("ErrorDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property SMErrorFixer_Icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SMErrorFixer_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
